### ISSUE TITLE
[FEAT] API 고급 - 컬렉션 조회 최적화

### ISSUE THREAD

**Issue by jimin-kiim** [serverstudy/KimJimin#11]
## About

- 주문내역 조회 기능에 추가로 일대다 관계인 주문한 상품 정보를 조회하고 성능을 최적화한다. 

## Branch Name

#11

## To do

- [x] 주문 상품 정보 조회 및 최적화

**Comment by kimchaeeun3447** [comment]
우리...언제 다시 돌아올까요..~~?? ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ ㅎㅎ...... @jimin-kiim

**Comment by jimin-kiim** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ오늘 해야겠당 ...

**Comment by kimchaeeun3447** [comment]
모야 진짜헀엌ㅋㅋㅋ ㅠㅠ

**Comment by jimin-kiim** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ한 달 만에 한 거였엉ㅋㅋㅋㅋㅋ ㅜㅜ
