### ISSUE TITLE
[FEAT] 스프링 데이터 JPA, QueryDSL 개요

### ISSUE THREAD

**Issue by jimin-kiim** [serverstudy/KimJimin#14]
## About

- 스프링 데이터 JPA와 queryDSL의 개요를 이해한다. 

## Branch Name

feat/#14

## To do

- [x] 스프링 데이터 JPA 개요 이해 
- [x] queryDSL 개요 이해

**Comment by kimchaeeun3447** [comment]
뿌잉뿌잉
